FROM linuxbrew/brew:latest

RUN brew install groff
RUN brew install libyaml
RUN brew install python@3.10

RUN brew install zip
RUN brew install awscli

RUN brew tap aws/tap
RUN brew install aws-sam-cli
