FROM nsidc/aws-sam-cli-build-image-python3.10:latest

USER root

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH "$PATH:/root/.local/bin:/home/linuxbrew/.local/bin"

COPY sam_build.sh /sam_build.sh

CMD ls /home/runner/work/cumulus_cmr_metadata_generator/cumulus_cmr_metadata_generator/cumulus_cmr_metadata_generator/src/ -l && /sam_build.sh
