name: check

on: push

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8.x'
      - run: pip install shellcheck-py
      - run: ./run_tests.sh
      